<?php
/**
 * @file
 *
 */

/**
 * Implementation of hook_menu().
 *
 */
function gateway_twitter_menu() {
  
  $items = array();
  
  $items['admin/config/services/gateway-twitter'] = array(
    'title' => t('Gateway Twitter Settings'),
    'access arguments' => array('access administration pages'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gateway_twitter_admin'),
    'file' => 'gateway_twitter.admin.inc'
  );
  
  return $items;
} // end function gateway_twitter_menu;

/**
 * Implementation of hook_block_info().
 *
 */
function gateway_twitter_block_info() {
  
  $blocks = array();
  $blocks['gateway_twitter']['info'] = t('Latest Tweet Block');
  
  return $blocks;

}// end function gateway_twitter_block_info;

/**
 * Implementation of hook_block_view().
 *
 */
function gateway_twitter_block_view($delta = '') {
  
  
  $block = array();
  
  switch($delta) {
    
    case 'gateway_twitter':
      $block['subject'] = variable_get('gateway_twitter_title', t(''));
//      $block['subject'] = 'Latest Tweet';
      $block['content'] = _gateway_twitter_block_content($delta);
      break;
  }
  
  return $block;
}// end function gateway_twitter_block_view;


function _gateway_twitter_block_content($delta = '') {
  
/*  $format = '';
  $msg_format = variable_get('jquery_countdown_msg_format', '');
  
  $format .= preg_match("/%years/", $msg_format)? 'Y' : $format;
  $format .= preg_match("/%months/", $msg_format)? 'O' : $format;
  $format .= preg_match("/%weeks/", $msg_format)? 'W' : $format;
  $format .= preg_match("/%days/", $msg_format)? 'D' : $format;
  $format .= preg_match("/%hours/", $msg_format)? 'H' : $format;
  $format .= preg_match("/%minutes/", $msg_format)? 'M' : $format;
  $format .= preg_match("/%seconds/", $msg_format)? 'S' : $format;
  $event_name = variable_get('jquery_countdown_event_name', '');
  
  $until = date("F d, Y g:i a", strtotime(variable_get('jquery_countdown_target', '')));

  if (variable_get('jquery_countdown_until', 1)) {
    $description = t('Until @event_name', array('@event_name' => $event_name));
  }
  else {
    $description = t('');
  }
  */
//  $url_feed = variable_get('gateway_twitter_feed_url', 'http://twitter.com/statuses/user_timeline/gatewaypeople.json?callback=twitterCallback2&count=3');
  $search = variable_get('gateway_twitter_search_string', 'from:gatewaypeople');
  $interval = variable_get('gateway_twitter_interval', '30000');
  $title = variable_get('gateway_twitter_title', 'Latest Tweets');
  $caption = variable_get('gateway_twitter_caption', 'GatewayPeople');
  $width = variable_get('gateway_twitter_width', 'auto');
  $height = variable_get('gateway_twitter_height', '300');
  $shell_background = variable_get('gateway_twitter_shell_background', '#8ec1da');
  $shell_color = variable_get('gateway_twitter_shell_color', '#ffffff');
  $tweets_background = variable_get('gateway_twitter_tweets_background', '#ffffff');
  $tweets_color = variable_get('gateway_twitter_tweets_color', '#444444');
  $tweets_links = variable_get('gateway_twitter_tweets_links', '#1985b5');
  $options = array(
//    'url_feed' => $url_feed,
    'search' => $search,
    'interval' => $interval,
    'title' => $title,
    'caption' => $caption,
    'width' => $width,
    'height' => $height,
    'shell_background' => $shell_background,
    'shell_color' => $shell_color,
    'tweets_background' => $tweets_background,
    'tweets_color' => $tweets_color,
    'tweets_links' => $tweets_links,
  );
  
  return theme('gateway_twitter', array('options' => $options, 'id' => 'gateway_twitter-' . $delta ));
}// end function _gateway_twitter_block_content;

/**
 * Implementation of hook_theme().
 */
function gateway_twitter_theme($existing, $type, $theme, $path) {
  return array(
    'gateway_twitter' => array(
      'variables' => array(
        'options' => NULL,
        'id' => NULL,
        'content' => NULL,
      ),
    ),
  );
}

/**
 * Constructs a jQuery Countdown element and adds the required JavaScript.
 *
 * @param $content
 *   (optional) The initial content to put in the countdown. This is what is shown
 *   when JavaScript is not available.
 * @param $options
 *   (optional) The options to apply to the element.
 * @param $id
 *   (optional) The name of the element.
 */
function theme_gateway_twitter($variables) {
  //@TODO: add javascript fallback for target time as possible $content ?!
  $id = $variables['id'];
  $options = $variables['options'];
  $content = $variables['content'];

  // Construct the ID name and add the JavaScript.
  $id = drupal_html_id($id);
  // add the Javascript
//  jquery_countdown_add('#'. $id, $options);

  // Construct the HTML.
//  dsm($options);
  
  // fall back "fall back" -nothing #dst from:gatewaypeople OR from:gateway_men
  
  // Search Widget
  return "<script src=\"http://widgets.twimg.com/j/2/widget.js\"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'search',
  search: '" . $options['search'] . "',
  interval: " . $options['interval'] . ",
  title: '" . $options['title'] . "',
  subject: '" . $options['caption'] . "',
  width: '" . $options['width'] . "',
  height: '" . $options['height'] . "',
  theme: {
    shell: {
      background: '" . $options['shell_background'] . "',
      color: '" . $options['shell_color'] . "'
    },
    tweets: {
      background: '" . $options['tweets_background'] . "',
      color: '" . $options['tweets_color'] . "',
      links: '" . $options['tweets_links'] . "'
    }
  },
  features: {
    scrollbar: false,
    loop: true,
    live: true,
    behavior: 'default'
  }
}).render().start();
</script>";
/*
  // Profile Widget
  return "<script src=\"http://widgets.twimg.com/j/2/widget.js\"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 3,
  interval: 30000,
  width: 'auto',
  height: 200,
  theme: {
    shell: {
      background: '#333333',
      color: '#ffffff'
    },
    tweets: {
      background: '#000000',
      color: '#ffffff',
      links: '#4aed05'
    }
  },
  features: {
    scrollbar: false,
    loop: false,
    live: true,
    behavior: 'all'
  }
}).render().setUser('gateway_men').start();
</script>";
  return '<!-- Latest Tweet BEGIN -->
<div id="twitter_div"><ul id="twitter_update_list"></ul></div> 
	<script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
        <script type="text/javascript" src="' . $options['url_feed'] . '"></script>
<!-- Latest Tweet END -->';*/
}

